version: '3.5'
services:
  nginx_dev:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx
      - ./platformweb-selfsigned.crt:/etc/ssl/certs/platformweb-selfsigned.crt
      - ./platformweb-selfsigned.key:/etc/ssl/private/platformweb-selfsigned.key
    ports:
      - 80:80
      - 443:443
    networks:
      - bravendev

# Note all Braven web app docker dev envs use this same network so they can talk to each other.
# E.g. the hostname joinweb will resolve inside the ssoweb container if they are on the same docker network.
networks:
  bravendev:
    name: braven_dev_network
